### ISSUE TITLE
Error Initializing Hydride in Android

### ISSUE THREAD

**Issue by lucas2412** [libly/hydride-java#1]
Hello,

I'm trying to integrate this library in my Android App but I'm not able to get it working.
I added  `maven { url 'https://jitpack.io' }` to my repository file and `implementation 'com.github.libly:hydride-java:1.1.1'` to my gradle dependecies.

Now when im trying to init Hydride with `Hydrogen hydrogen = new Hydrogen();` im getting following error. Is there something I'm missing here? 

```
co.libly.hydride.utils.LibraryLoadingException: Unsupported platform: Linux/aarch64

**Comment by gurpreet-** [comment]
HI @lucas2412,

Thank you for your comment. 

So as this is a Java project and not an Android project, Hydride won't work if you add it to an Android project. I can add Android support no problem 😄but it may take some time (up to 2 weeks).

**Comment by lucas2412** [comment]
Oh ok. I was wondering because in the description it says that **Android 16 and above** is supported. 
It would be really nice if you add Android support since I found no other lib that offers libhydrogen functionality for Android.

**Comment by gurpreet-** [comment]
Sure, I'll get working on it right away 👍

**Comment by lucas2412** [comment]
Hey, did you already make some progress?
Thank you :)

**Comment by gurpreet-** [comment]
Hi @lucas2412,

Yes I have made a lot of progress. I have successfully created Hydride for Android: https://github.com/libly/hydride-android

It is a very new library and I got some more work to do on it like adding tests and testing it on various devices. But I think it should work! Let me know if it works for you 😄

**Comment by lucas2412** [comment]
Thanks a lot. I will try it out on monday and let you know if it works!

**Comment by gurpreet-** [comment]
I assume this worked for you @lucas2412. Closing.
